version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Europe/Sofia"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 3
    assignees:
      - sagar-kap

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Europe/Sofia"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 3
    assignees:
      - sagar-kap

  - package-ecosystem: "npm"
    directory: "./docs"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Europe/Sofia"
    commit-message:
      prefix: "chore(docs): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 3
    assignees:
      - sagar-kap
