package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var createPath string

const starterManifest = `{
  "name": "Example Template",
  "description": "A starter template generated by terox create",
  "variables": [
    { "name": "project_name", "prompt": "Project name", "default": "my-project" },
    { "name": "author",       "prompt": "Author",       "default": "" },
    { "name": "license",      "prompt": "License",      "default": "MIT",
      "choices": ["MIT", "Apache-2.0", "GPL-3.0", "None"] }
  ]
}
`

const starterReadme = `# {{.project_name}}

By {{.author}}

Licensed under {{.license}}.
`

const starterGitignore = `node_modules/
dist/
.env
`

var createCmd = &cobra.Command{
	Use:     "create <template-name>",
	Short:   "Create a project template",
	Long:    "Create a starter template directory with a terox.json manifest and example files.",
	Example: `  terox create simple-website --path ./templates`,
	Args:    cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		root, err := filepath.Abs(filepath.Join(createPath, name))
		if err != nil {
			return fmt.Errorf("resolve template path: %w", err)
		}
		return createTemplate(name, root)
	},
}

func createTemplate(name, root string) error {
	fmt.Printf("Creating template %q at %s\n", name, root)

	if err := os.MkdirAll(root, 0o755); err != nil {
		return fmt.Errorf("create template dir: %w", err)
	}

	manifest := filepath.Join(root, "terox.json")
	if err := os.WriteFile(manifest, []byte(starterManifest), 0o644); err != nil {
		return fmt.Errorf("write terox.json: %w", err)
	}

	projectDir := filepath.Join(root, "{{.project_name}}")
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		return fmt.Errorf("create project dir: %w", err)
	}

	if err := os.WriteFile(
		filepath.Join(projectDir, "README.md"),
		[]byte(starterReadme), 0o644,
	); err != nil {
		return fmt.Errorf("write README.md: %w", err)
	}

	if err := os.WriteFile(
		filepath.Join(projectDir, ".gitignore"),
		[]byte(starterGitignore), 0o644,
	); err != nil {
		return fmt.Errorf("write .gitignore: %w", err)
	}

	fmt.Println("Done. Edit terox.json to add variables; edit files under")
	fmt.Println(projectDir, "to add your template body.")
	return nil
}

func init() {
	cwd, _ := os.Getwd()
	createCmd.Flags().StringVar(
		&createPath, "path", cwd,
		"directory to create the template under (default: cwd)",
	)
	rootCmd.AddCommand(createCmd)
}
