name: Deploy Documentations

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build the Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Install & Build the Docs
        uses: withastro/action@v5.2.0
        with:
          path: docs
          package-manager: pnpm

  deploy:
    name: Deploy the Docs
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
